---
title: "Administrative summary"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    smooth_scroll: true
    css: style.css
---

```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
library(tidyr)
library(dplyr)
library(purrr)
library(DT)
library(shiny.semantic)
library(shiny)
library(htmltools)
library(crosstalk)
```

```{r layout, include=FALSE}
max_intermediate_levels <- 50

plot_colors <- c('#5A0A69', '#62B200')

bar_plot_margins <- list(
  l = 70,
  r = 50,
  b = 70,
  t = 10,
  pad = 4
)
```

```{r}
load("../assets/admin_report_input.RData")
source("../plots/ploting.R")
source("../munging/munging.R")
```

```{r}
last_12_weeks_report_status <- admin_report_input$reportingValues_W12 %>%
  round_review_report()

last_12_weeks_level_2 <- last_12_weeks_report_status %>%
  dplyr::filter(level == 1) %>%
  mutate(
    year = ifelse(week < 8, 2018, 2017), # This is temporary - year column needs to be in the raw data
    year_week = paste0(year, " - W", week))

min_year <- min(last_12_weeks_level_2$year)
max_year <- max(last_12_weeks_level_2$year)

 min_week <- last_12_weeks_level_2 %>%
  filter(year == min_year) %>%
  pull(week) %>% min()
 
max_week <- last_12_weeks_level_2 %>%
  filter(year == max_year) %>%
  pull(week) %>% max()

last_12_weeks_level_1_long <- last_12_weeks_level_2 %>%
  select(Id_Site, year_week, week, compReport, timeReport, reference) %>% 
  gather(key = label, value = number, -Id_Site, -year_week, -week, -reference) %>%
  mutate(label = recode_report(label))
```

<style>                     
.navbar {
  background-color:#5A0A69;
  border-color:black;
}
</style>

Row
-------------------------------------

### Completeness and timeliness of weekly reporting for the whole country

```{r}
last_12_weeks_level_1_long %>%
    plot_reporting_central_level(plot_colors)
```


Row
-------------------------------------
### Overall completeness and timeliness of weekly reporting from week `r paste0(min_week, " (", min_year, ")")` to `r paste0(max_week, " (", max_year, ")")`

```{r}
overall_12_weeks_report_status <- admin_report_input$reportingValues_W12_overall %>%
  round_review_report()

first_intermediate_level <- overall_12_weeks_report_status$level %>% max()

count_levels <- overall_12_weeks_report_status %>%  group_by(level) %>% count()
count_first_intermediate_level <- count_levels %>% filter(level == first_intermediate_level) %>% pull(n)

selected_level <- ifelse(count_first_intermediate_level < max_intermediate_levels, first_intermediate_level, first_intermediate_level + 1)

parent_sites <- overall_12_weeks_report_status %>%
  dplyr::filter(level == selected_level) %>%
  select(compReport, timeReport, Id_Site, reference, FK_ParentId) %>% 
  gather(key = label, value = number, -Id_Site, -reference, -FK_ParentId) %>%
  mutate(label = recode_report(label),
         parent_label = factor(paste(FK_ParentId, reference, sep = "_"))) %>%
  arrange(parent_label)

order_sites <- unique(parent_sites$parent_label)

parent_sites %>%
  plot_1st_itermediate_level(plot_colors = plot_colors,
                             margins = bar_plot_margins,
                             order_x = order_sites,
                             x_title = '',
                             y_title = '%')
```

Row
-------------------------------------

### Overall completeness and timeliness of data review at each level from week `r paste0(min_week, " (", min_year, ")")` to `r paste0(max_week, " (", max_year, ")")`

```{r}
reviewing_sites <- overall_12_weeks_report_status

reviewing_sites_long <- reviewing_sites %>%
  select(compReview, timeReview, FK_ParentId, reference, level) %>% 
  gather(key = label, value = number, -reference, -FK_ParentId, -level) %>%
  mutate(label = recode_review(label)) %>%
  arrange(level)

order_sites_review <- unique(reviewing_sites_long$reference)

plots_above_first_intermediate_level <- reviewing_sites_long %>%
  filter(level < first_intermediate_level) %>%
  plot_1st_itermediate_level(plot_colors = plot_colors,
                             margins = bar_plot_margins,
                             order_x = order_sites_review,
                             x_title = '',
                             y_title = '%',
                             is_show_legend = FALSE)

reviewing_sites_long_1st_intermediate_level <-  reviewing_sites_long %>%
  filter(level == first_intermediate_level)

reviewing_sites_long_1st_intermediate_level %>% 
  split(reviewing_sites_long_1st_intermediate_level$FK_ParentId) %>%
  map(function(df){
    plot_1st_itermediate_level(data = df, plot_colors = plot_colors,
                             margins = bar_plot_margins,
                             order_x = order_sites_review,
                             x_title = '',
                             y_title = '%',
                             is_show_legend = FALSE) }) -> plots_first_intermediate_level

plots_first_intermediate_level[[1]]$x$attrs[[1]]$showlegend <- TRUE
nrow_charts <- ceiling(max(length(plots_first_intermediate_level)/2, 1))

subplots_plots_first_intermediate_level <- plots_first_intermediate_level %>%
  subplot(nrows = nrow_charts, titleX = TRUE, titleY = TRUE, margin = 0.15)

subplot(plots_above_first_intermediate_level, subplots_plots_first_intermediate_level,
        nrows = nrow_charts + 1)
```


Row
-------------------------------------

### Silent sites: reporting sites with no reports received for 8 weeks and longer

```{r}
sites_no_report_3weeks <- admin_report_input$noReport_W3 %>%
  select(`Area` = name_parentSite,
         `Site name` = siteName,
         Contact = contact,
         Phone = phone)

sites_no_report_8weeks <- admin_report_input$noReport_W8 %>%
  select(`Area` = name_parentSite,
         `Site name` = siteName,
         Contact = contact,
         Phone = phone)
  
datatable(data = sites_no_report_8weeks, extensions = 'Buttons',
          options = list(
            dom = 'tpB', buttons = c('copy', 'csv', 'excel', 'pdf', 'print')))

```

### Silent sites: reporting sites with no reports received for 3 weeks and longer

```{r}
datatable(data = sites_no_report_3weeks, extensions = 'Buttons',
          options = list(
            dom = 'tpB', buttons = c('copy', 'csv', 'excel', 'pdf', 'print')))

```
