---
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    smooth_scroll: true
    css: style.css
    theme: cosmo
    self_contained: false
    mathjax: NULL
params:
  custom_title: "Epidemiological summary"
title: "`r params$custom_title`"
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny.i18n)

## file with translations
i18n <- Translator$new(translation_csvs_path = "../translations",
                       translation_csv_config = "../translations/config.yaml")

## set translation language
i18n$set_translation_language(language)

load("../assets/epi_report.Rdata")
```

<style>                     
.navbar {
  background-color:#5A0A69;
  border-color:black;
}
</style>

Row
-------------------------------------

### `r i18n$t("disease_charts_header")`

```{r subplots_disease_occurance_w12, echo = FALSE, results = TRUE, message = FALSE, warning = FALSE, error = FALSE, dev='svg', fig.width = 7, fig.asp = 1.3, fig.path ='../assets/'}
disease_occurance_w12 %>%
  plot_occurance(., plot_colors[1],
                      x_title = i18n$t("epi_week_nb"),
                      y_title = i18n$t("nb_of_cases"),
                 max_occurence)
```

### `r i18n$t("disease_maps_header")`

```{r maps, echo = FALSE, results = TRUE, message = FALSE, warning = FALSE, error = FALSE, dev='svg', fig.width = 7, fig.asp = 1.3, fig.path ='../assets/'}
plot_maps(country_data, disease_location)
```

<script type="text/javascript">
(function() {
    var randomValue = Math.floor((Math.random() * 1000000) + 1);
    var images = document.getElementsByTagName("img");
    for (index in images) {
        var image = images[index];
        image.src = image.src + "?cacheResetValue=" + randomValue;
    }
})()
</script>


Row
-------------------------------------

### `r i18n$t("disease_table_occurence_header")`

```{r}
DT::datatable(data = disease_occurance_above_threshold,
              extensions = "Responsive",
              rownames = FALSE,
              options = list(
                columnDefs = list(list(responsivePriority = 1, targets = 0)),
                dom = 'tp'))
```

### `r i18n$t("disease_table_alerts_header")`
```{r}
DT::datatable(data = alert_list_D10,
              extensions = "Responsive",
              rownames = FALSE,
              options = list(
                columnDefs = list(list(responsivePriority = 1, targets = 0)),
                dom = 'tp'))
```

Row
-------------------------------------

### `r i18n$t("disease_table_cumulative_header")`

```{r}
DT::datatable(data = cumulative_table,
               extensions = "Responsive",
              rownames = FALSE,
              options = list(
                columnDefs = list(list(responsivePriority = 1, targets = 0)),
                dom = 'tp'))
```
